on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include: 
          - os: ubuntu-latest
            zip-name: kattis-${{ github.event.release.tag_name }}-linux.zip
            zip-cmd: zip --junk-paths kattis-${{ github.event.release.tag_name }}-linux.zip test
          - os: macos-latest
            zip-name: kattis-${{ github.event.release.tag_name }}-macos.zip
            zip-cmd: zip --junk-paths kattis-${{ github.event.release.tag_name }}-macos.zip test
          - os: windows-latest
            zip-name: kattis-${{ github.event.release.tag_name }}-windows.zip
            zip-cmd: Compress-Archive -LiteralPath test -DestinationPath kattis-${{ github.event.release.tag_name }}-windows.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      
    - name: Install latest stable Cargo
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    #- name: Run cargo build
      #uses: actions-rs/cargo@v1
      #with:
        #command: build
        #args: --release
        
    - name: zip artifacts
      run: |
        echo "This is a test" > test
        ${{ matrix.zip_cmd }}
    - name: Upload artifacts
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ matrix.zip-name }}
        asset_name: ${{ matrix.zip-name }}
        asset_content_type: application/zip
